Updates and corrections to index.html
EnderSmith/EnderSmith.github.io pull request #1
Opened 2017-07-29 15:55 UTC by MikeJenson

Corrected link to chord progression generator.
Added link to new Dice Roll Calculator.

2017-07-31 00:47 UTC, EnderSmith submitted a review, later dismissed
Thanks for these changes!

2017-07-31 01:33 UTC, EnderSmith requested changes
Thanks for contributing!
I noticed that the back links need to be relative to the parent folder.

2017-07-31 01:33 UTC, EnderSmith commented on ChordProgress/ChordProg.htm
> +    <a href="index.html">
i think this needs to be a relative link to the folder above it or a full url:
`<a href="../index.html">`

2017-07-31 01:33 UTC, EnderSmith commented on clrKnit/clrKnit.html
> +    <a href="index.html">
same thing, relative or full url:
`<a href="../index.html">`

2017-07-31 01:33 UTC, EnderSmith commented on diceRoll/diceRoll.html
> +    <a href="index.html">
same thing, relative or full url:
`<a href="../index.html">`

2017-07-31 01:33 UTC, EnderSmith commented on index.html
> +    <a href="ChordProgress/ChordProg.html">
thanks for finding that!

2017-07-31 01:33 UTC, EnderSmith commented on payclock.html
> +    <a href="index.html">
(this one is correct. I need to move into its own folder like the others!)

2017-07-31 03:56 UTC, MikeJenson commented
I believe you're correct on that actually, I've not worked much with html in folders, I think that having it link back to the full URL would be best just to make it "future proof" so you wouldn't need to change if you change the folder layout

2017-07-31 05:29 UTC, MikeJenson commented
I've run through and made all requested changes. I have also moved the "payclock" files into their own folder.

2017-07-31 05:32 UTC, MikeJenson reviewed
These requests have now been fulfilled.

2017-08-02 02:06 UTC, EnderSmith approved these changes
It's possible we'll have to go back and add direct links to the back home buttons to keep them futureproof

2017-08-02 02:06 UTC, merged